# 实验室实验：政治科学研究的一种有效方法？

## 摘要

因果推断，实验室试验严格遵循因果逻辑

以往人们认为是“内高外低”，实验室实验设计可以实现内部效度和外部效度“双高”

## 引言

21世纪以来，政治科学研究趋势逐渐由相关性走向因果性

时间序列分析，断点回归，双重差分等方法都是因果分析方法

实验法用于因果推断格外有效

国内研究者对实验法兴趣很大，但大多集中于调查实验和田野实验，实验室实验却很少

## 实验逻辑与政治学实验室实验

实验是建立在遵循反事实逻辑上的因果推断（对照组代表了一个假设条件，即如果不使用肥料，植物的生长情况会如何，这种逻辑帮助我们对比因果关系）

### 实验逻辑

内曼-鲁宾因果理论：什么是因果效应？（条件存在时发生的效果）-（条件不存在时可能发生但未发生的结果）=因果效应

但是不可能同时观测，只能谋求群体层面对因果效应进行估测

个体处理稳定性假定：干预因素对群体内个体的作用具有针对性（只会改变单一个体，对其他个体没影响）和同质性（改变的幅度是一致的）

自然实验法难以招架：很难保证干预因素对单一个体的作用不会影响到同一目标人群中的其他成员

实验法可以满足个体处理稳定性假定

### 实验室实验

实验逻辑在实证研究中的三种形式：田野，调查，实验室

实验室实验对场地和时间有更严格的控制，通常是在独立实验室中进行，实验过程受到研究者的监控和指导，接近于自然实验

实验的原则：确定目标人群和干预因素，随机分配控制组和实验组

### 实验室中的政治科学研究

1950年左右获得学界的广泛重视，行为主义革命

也有一些学者认为实验室实验过于依赖人工设计，而且被试不能代表任何目标人群

当前实验政治学的三种独特模式：政治心理学，政治经济学，统计学

政治心理学：通过精心筛选和制作的干预信息，比如政治新闻，将被试带入一个想象性情景，并要求做出特定决策

e.g. 政治传播中的反动员效应：播报候选人是否同意近海石油开采，实验组是反对摧毁，控制组是保护同意等正面词汇，发现实验组的人更不愿意参与投票

## 效度最大化？实验设计的规范和谬误

### 研究效度

基于该设计作出的知识推断和真实情况具有近似性，即我们能在多大程度上相信实证推断能够反映人类社会的真实规律

内部效度：基于实证研究的知识推断与目标人群的真实态度和行为规律的近似程度

外部效度：实证推断多大程度能适用于目标人群以外的人群

之前的诟病：内高外低

内高：实验设计对干扰变量的控制很有力

外低：被试样本的非代表性与。实验室环境与现实环境的明显差异

**内高不一定**，很多文章的结果都不能复刻

随机分配不能排除所有的干扰变量，控制组和实验组的干扰因素无法完全一致

新的工具：行为心理学的方法，计算机成像技术、脑部核磁共振等等

**外低也不一定**

实验室效应

新的视角，生态效度

五种方法缓解：掩盖实验目的，使用现实的例子作为干扰变量，模拟现实环境，物质刺激，非自然环境或许就是某些实验需要的


